# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gke_databases_data_cache_01_sc_storage_class_balanced]
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hd-balanced-data-cache
provisioner: pd.csi.storage.gke.io
parameters:
  type: hyperdisk-balanced
  data-cache-mode: writethrough
  data-cache-size: "150Gi"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
# [END gke_databases_data_cache_01_sc_storage_class_balanced]

